# Generated by Django 5.0.4 on 2024-05-12 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_image_product_image1_remove_cart_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='additional_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Home', 'Home'), ('Accessories', 'Accessories')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
