# Generated by Django 5.0.4 on 2024-05-12 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
